#! /bin/bash

g++ -o test.o Test.cpp Debug.cpp ../process/ProcessData.cpp ../midi/MidiSwitch.cpp ../util/CircularBuffer.cpp ../util/DCT.cpp ../util/Stats.cpp ../util/Tuning.cpp ../util/Waveforms.cpp -ggdb