#! /bin/bash
UtilSrc=("CircularBuffer.cpp" "DCT.cpp" "Stats.cpp" "Tuning.cpp" "Waveforms.cpp")
MidiSrc=("MidiSwitch.cpp")
ProcSrc=("ProcessData.cpp")
TestSrc=("Debug.cpp")

Path="/mnt/e/Projects/Scribe/src/"
UtilPath="util/"
MidiPath="midi/"
ProcPath="process/"

Src=""
Headers=""

for s in ${UtilSrc[@]}; do
  Src+="../"${UtilPath}${s}" "
done

for s in ${MidiSrc[@]}; do
  Src+="../"${MidiPath}${s}" "
done

for s in ${ProcSrc[@]}; do
  Src+="../"${ProcPath}${s}" "
done


g++  -I ${Path}${UtilPath} -I ${Path}${MidiPath} -I ${Path}${ProcPath} -o test.o Test.cpp Debug.cpp -ggdb ${Src}
